name: GitHub Activity

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day
  workflow_dispatch: # Allows manual trigger

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Basic settings
          user: Obaid03
          template: classic
          base: header, activity, community, repositories, metadata

          # Commit activity breakdown (Morning, Daytime, Night)
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          # Output file name
          filename: activity.svg
