name: GitHub Activity

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day
  workflow_dispatch: # Allows manual trigger

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Basic settings
          user: Obaid03
          template: classic
          base: header, activity, community, repositories, metadata

          # Commit activity breakdown (Morning, Daytime, Night)
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

      - name: Save Activity SVG
        run: mv metrics.plugin-habits.svg activity.svg

      - name: Upload Activity SVG to Repository
        uses: actions/upload-artifact@v3
        with:
          name: activity
          path: activity.svg
