name: GitHub Activity Metrics

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day
  workflow_dispatch: # Allows manual trigger

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Activity Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Basic settings
          user: Obaid03
          template: classic
          base: header, activity, community, repositories, metadata

          # Commit activity breakdown
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no  # ❌ Disable charts
          plugin_habits_trim: yes   # ✅ Enable text-based display
