name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Ensures workflow has access to repo

      - name: Generate Snake GIF
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Obaid03
          outputs: dist/github-contribution-grid-snake.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # ✅ Updated to v4
        with:
          name: snake-gif
          path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated snake contribution graph" || echo "No changes to commit"
          git branch -M output  # Ensure branch name is correct
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
