name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Runs every 24 hours
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Obaid03
          template: classic
          base: activity
          config_timezone: Asia/Karachi
