name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day
  workflow_dispatch: # Allows manual trigger

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          # GitHub token with public_repo scope
          token: ${{ secrets.METRICS_TOKEN }}

          # Basic settings
          user: Obaid03
          template: classic
          base: header, activity, community, repositories, metadata

          # Language statistics
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming
          plugin_languages_limit: 8
          plugin_languages_recent_days: 30

          # Activity breakdown (morning, evening, etc.)
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
